import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
    <script src="https://cdn.tailwindcss.com"></script>
    <script
          src="https://widget.Cloudinary.com/v2.0/global/all.js"
          type="text/javascript"
        ></script>
    </head>
    <body className={inter.className}>
    <Suspense fallback={<div>Loading...</div>}>
            
            {children}
        </Suspense>
     
    
    </body>
  </html>
  );
}
